// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/data/yjlee/PhysicsZHadronEEC/TrackingEfficiency/20240806_ResidualCorrection/workflow/./plot_corrections.C";

#endif
